from enum import StrEnum


class DivisionCode(StrEnum):
    FINANCE = "FINANCE"
    SALES_MARKETING = "SALES_MARKETING"
    PROPERTY = "PROPERTY"
    HR = "HR"
    LEGAL = "LEGAL"
    IT = "IT"


class HumanRole(StrEnum):
    DIRECTOR = "DIRECTOR"
    DIVISION_OWNER = "DIVISION_OWNER"
    IT_LEAD = "IT_LEAD"
    TECHNICAL_REVIEWER = "TECHNICAL_REVIEWER"
    BUSINESS_REVIEWER = "BUSINESS_REVIEWER"
    QA_SECURITY = "QA_SECURITY"


class SystemActor(StrEnum):
    GENESIS = "GENESIS"
